config = {"data-file":"./data/celeba_64.hdf5",
          "model-file":"./model/epoch_30.h5",
          "feature-file":"./feature.txt",
          "model-path":"./model/",
          "epochs":500,
          "batchs":128,
          "train-datasets":5000,
          "img-shape":(64,64,3),
          "feature-dim": 40,
          "noise-dim": 40,
          "train":False,
          "GPU-number":"1",
          "env":"GPU"}

def get_config(para,default = None):
    try:
        value = config[para]
    except:
        value = default
    return value

feature_map = {"5_o_Clock_":1,
               "Arched_Eyebrows":2,
               "Attractive":3,
               "Bags_Under_Eyes":4,
               "Bald":5,
               "Bangs":6,
               "Big_Lips":7,
               "Big_Nose":8,
               "Black_Hair":9,
               "Blond_Hair":10,
               "Blurry":11,
               "Brown_Hair":12,
               "Bushy_Eyebrows":13,
               "Chubby":14,
               "Double_Chin":15,
               "Eyeglasses":16,
               "Goatee":17,
               "Gray_Hair":18,
               "Heavy_Makeup":19,
               "High_Cheekbones":20,
               "Male":21,
               "Mouth_Slightly_Open":22,
               "Mustache":23,
               "Narrow_Eyes":24,
               "No_Beard":25,
               "Oval_Face":26,
               "Pale_Skin":27 ,
               "Pointy_Nose":28 ,
               "Receding_Hairline":29 ,
               "Rosy_Cheeks":30 ,
               "Sideburns":31 ,
               "Smiling":32 ,
               "Straight_Hair":33 ,
               "Wavy_Hair":34 ,
               "Wearing_Earrings":35 ,
               "Wearing_Hat":36 ,
               "Wearing_Lipstick":37 ,
               "Wearing_Necklace":38 ,
               "Wearing_Necktie":39 ,
               "Young":40}
